servo-rancher:
  project: "Default"
  environment:
    MEMORY:
     type: int
     min: 4096
     max: 16384
     step: 64
     scale: M
     multiplier: ''
     wrapper: ''
    GC:
      type: enum
      values:
        Serial:
          -XX:+UseSerialGC
        Parallel:
          -XX:+UsePArallelGC -XX:ParallelGCThreads=10
        CMS:
          -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:CMSInitiatingOccupancyFraction=50 -XX:+UseCMSInitiatingOccupancyOnly
        G1:
        -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC
  compose:
   cpu-reservation:
     type: float
     min: 0.10
     max: 2.00
     step: 0.1
     multiplier: '1'
   memory-reservation:
     type: int
     min: 4096
     max: 16384
     step: 256
     multiplier: '1024'
   count:
     type: int
     min: 1
     max: 10
     step: 1
     multiplier: '1'
