rancher:
  project: "Default"
  stack: "http-test"
  api_url: "http://rancher.kumulus.co:8080/v2-beta"
  # api_key: "ABCDEFG"
  # api_secret: "HIJKLMNO"
  service:
    defaults:
      environment:
        MEMORY:
          min: 512
          max: 16384
          step: 64
          template: "MEMORY: '{{parameter}}M'"
      memoryMb:
          min: 512
          max: 16384
          step: 64
      vcpu:
        min: 1
        max: 10
    front:
      environment:
        GC:
          template: "GC: '-XX:+UsePArallelGC -XX:ParallelGCThreads={{parameter}}'"
    http-slb:
      exclude: true

  excluded:
    - http-slb
