# This is a sample configuration for a Rancher service. It defines the operating parameters for
# each service. It is not a required file, and by default, the servo will be allowed to pass
# any values it wants for environment, memory, cpu, and scale
rancher:
  stack: "http-test"                                # Stack to operate on, not required
  project: "Default"                                # Override for OPTUNE_PROJECT env
  api_url: "http://rancher.kumulus.co:8080/v2-beta" # Override for OPTUNE_URL must include /v2-beta
  # api_key: "ABCDEFG"                              # Override for OPTUNE_API_KEY
  # api_secret: "HIJKLMNO"                          # Override for OPTUNE_API_SECRET

  # We currently only support Rancher services
  service:
    # This defines default values for all services
    defaults:
      memory:         # Defines a range for what the memory value can be. This is in Mb
          min: 512
          max: 16384
          step: 64
      cpu:            # Defines the number of  cpu cores
        min: 0.25
        max: 10
      scale:          # Defines how many instances of the service
        min: 1
        max: 10
    # Specific overrides for the 'front' service
    front:
      environment:
        GC:
          template: "GC: '-XX:+UsePArallelGC -XX:ParallelGCThreads={{parameter}}'"
    # Specific overrides for the 'back' service
    back:
      environment:
        MEMORY:
          min: 512
          max: 16384
          step: 64
      scale:
        min: 2
        max: 20
    # The 'http-slb' service is excluded
    http-slb:
      exclude: true
  # You may also exclude services this way
  excluded:
    - http-slb
