# This is a sample configuration for a Rancher service. It defines the operating parameters for
# each service. It is not a required file, and by default, the servo will be allowed to pass
# any values it wants for environment, memory, cpu, and scale
rancher:
  # stack: stack to operate on, not required
  # project: "Environment" in the UI, on which to find the stack(s) to operate on
  # api_url: In the event that the servo is not in the Rancher environment
  # api_key: as an alternative to passing the API key
  # api_secret: as an alternative to passing the API
  #
  # These initial parameters can also be defined as environment variables
  # OPTUNE_STACK
  # OPTUNE_PROJECT
  # OPTUNE_API_URL
  # OPTUNE_API_KEY
  # OPTUNE_API_SECRET

  stack: "http-test"
  project: "Default"
  api_url: "http://rancher.kumulus.co:8080/v2-beta"
  # api_key: "ABCDEFG"
  # api_secret: "HIJKLMNO"

  # We currently only support Rancher services
  services:
    # overrides for the 'front' service
    front:
    # specific envrionment parameters to add
    # If this parameter isn't already in the stack it is assumed to take
    # a wholy numeric parameter (e.g. 1024) as a value.  If the enviornment
    # variable already exists, then the first number will be extracted for
    # the --describe function, and the number will be replaced in the parameter
    # so an environment variable of MEMORY=1024M would become MEMORY=2048M
      environment:
        MEMORY:
          value: 2048M
    back:
      environment:
        MEMORY:
          value: 3072M
      scale:
        value: 2
      compute:
        value: 500
      memory:
        value: 4096
    # The 'http-slb' service is excluded
    http-slb:
      exclude: true
